name: "Setup"
description: "Set up Foundry and dependencies"

runs:
  using: "composite"
  steps:
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    - name: Install dependencies
      shell: zsh
      run: |
        make install

    - name: Show Forge version
      shell: zsh
      run: |
        forge --version
