name: Setup

env:
  FOUNDRY_PROFILE: default

on:
  workflow_call:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    - name: Install dependencies
      run: |
        make install
    
    - name: Show Forge version
      run: |
        forge --version
