name: Slither

on:
  push:
    branches:
      - main
      - release
      - develop
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: default

jobs:
  analyze:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
    - name: Setup Foundry environment
      uses: ./.github/workflows/reusable-steps/setup.yml

    - name: Run Slither
      uses: crytic/slither-action@v0.4.0
      with:
        slither-args: --config-file slither.config.json
