name: Slither

env:
  FOUNDRY_PROFILE: default

on:
  push:
    branches:
      - main
      - release
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  analyze:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Foundry and dependencies
      uses: ./.github/setup.yml

    - name: Run Slither
      uses: crytic/slither-action@v0.4.0
      with:
        slither-args: --config-file slither.config.json
