name: Slither

on:
  push:
    branches:
      - main
      - release
      - develop
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: default

jobs:
  analyze:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Run Reusable Setup Workflow
        uses: ./.github/workflows/setup.yml

      - name: Run Slither
        uses: crytic/slither-action@v0.4.0
        with:
          slither-args: --config-file slither.config.json